'use strict';
const p=window.PORTFOLIO, el=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
function safeLink(url){try{const u=new URL(url,location.href);return ['http:','https:','mailto:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function link(text,url,cls){const a=node('a',text,cls);const href=safeLink(url);if(href)a.href=href;if(href&&!href.startsWith('mailto:')&&new URL(href).origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';}return a;}
function earnedSkills(items){const box=node('div',null,'earned-skills');box.append(node('p','Key skills developed','skills-label'));const tags=node('div',null,'tags');(items||[]).forEach(t=>tags.append(node('span',t)));box.append(tags);return box;}
function filters(id,values,render){values.forEach((value,i)=>{const b=node('button',value);b.type='button';b.setAttribute('aria-pressed',String(i===0));b.addEventListener('click',()=>{el(id).querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render(value);});el(id).append(b);});render(values[0]);}
el('role').textContent=p.title;el('location').textContent=p.location;el('intro').textContent=p.introduction;el('about-copy').textContent=p.about;document.title=p.name+' | '+p.title;
const names=p.name.split(' ');document.querySelector('h1').replaceChildren(node('span',names.shift()),node('br'),node('em',names.join(' ')+'.'));
el('email').href='mailto:'+p.email;el('contact-email').href='mailto:'+p.email;el('contact-email').textContent=p.email+' ↗';el('socials').append(link('GitHub ↗',p.github),link('LinkedIn ↗',p.linkedin));el('copyright').textContent='© '+new Date().getFullYear()+' '+p.name;
if(p.resume&&safeLink(p.resume)){el('resume').hidden=false;el('resume').href=safeLink(p.resume);}if(p.portrait&&safeLink(p.portrait)){el('portrait').hidden=false;el('portrait').src=safeLink(p.portrait);el('monogram').hidden=true;}
p.hobbies.forEach(x=>{const a=node('article');a.append(node('h3',x.title),node('p',x.text));el('hobbies').append(a);});
filters('education-filters',['All','Master’s','Bachelor’s'],f=>{el('education-list').replaceChildren();p.education.filter(x=>f==='All'||(f==='Master’s'?x.degree.startsWith('M.'):x.degree.startsWith('B.'))).forEach(x=>{const d=node('details',null,'education-card');d.open=true;const summary=node('summary');summary.append(node('span',x.degree),node('span',x.dates,'meta'));d.append(summary,node('h3',x.institution),node('p',x.detail),node('p',x.location,'meta'),earnedSkills(x.skills));el('education-list').append(d);});});
let company='All';function renderExperience(){const q=el('experience-search').value.trim().toLowerCase();const items=p.experience.filter(x=>(company==='All'||x.company===company)&&[x.company,x.role,x.dates,x.location,...x.points,...(x.skills||[])].join(' ').toLowerCase().includes(q));el('experience').replaceChildren();el('experience-count').textContent=items.length+' of '+p.experience.length+' roles';items.forEach(x=>{const card=node('article',null,'experience-card');const meta=node('div',null,'experience-meta');meta.append(node('p',x.dates),node('span',x.location));const body=node('div');body.append(node('h3',x.company),node('p',x.role,'role'));const list=node('ul');x.points.forEach(t=>list.append(node('li',t)));body.append(list,earnedSkills(x.skills));card.append(meta,body);el('experience').append(card);});if(!items.length)el('experience').append(node('p','No matching roles. Try another search or choose All.','empty'));}
filters('experience-filters',['All',...new Set(p.experience.map(x=>x.company))],f=>{company=f;renderExperience();});el('experience-search').addEventListener('input',renderExperience);
function showSkill(name){const detail=el('skill-detail');detail.replaceChildren(node('h3',name));const matching=[];const matches=items=>(items||[]).some(t=>t.toLowerCase()===name.toLowerCase());p.experience.forEach(x=>{if(matches(x.skills))matching.push(x.company+' — '+x.role);});p.education.forEach(x=>{if(matches(x.skills))matching.push(x.degree+' — '+x.institution);});p.projects.forEach(x=>{if(matches(x.tags))matching.push('Project — '+x.title);});if(matching.length){detail.append(node('p','Used or developed in:'));const list=node('ul');matching.forEach(t=>list.append(node('li',t)));detail.append(list);}else detail.append(node('p','Part of my '+p.skills.find(g=>g.items.includes(name)).group.toLowerCase()+' toolkit.'));detail.hidden=false;}
filters('skill-filters',['All',...p.skills.map(x=>x.group)],f=>{el('skills').replaceChildren();el('skill-detail').hidden=true;p.skills.forEach((group,i)=>{if(f!=='All'&&f!==group.group)return;group.items.forEach(t=>{const tile=node('button',null,'skill-tile');tile.type='button';tile.setAttribute('aria-label','Explore '+t);tile.setAttribute('aria-pressed','false');tile.style.setProperty('--tile-accent',['#36b4a5','#bf79dc','#de9160','#678ed6'][i%4]);const mark=node('span',null,'skill-mark');mark.setAttribute('aria-hidden','true');const icon=p.skillIcons&&p.skillIcons[t];if(icon&&/^[a-z0-9-]+$/.test(icon)){const img=node('img');img.src='assets/icons/'+icon+'.svg';img.alt='';img.width=36;img.height=36;mark.append(img);}else mark.textContent='◇';tile.append(mark,node('span',t,'skill-name'),node('span',group.group,'skill-group'));tile.addEventListener('click',()=>{el('skills').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===tile)));showSkill(t);});el('skills').append(tile);});});});
filters('filters',['All',...new Set(p.projects.map(x=>x.category))],f=>{el('project-grid').replaceChildren();p.projects.forEach((x,i)=>{if(f!=='All'&&x.category!==f)return;const a=node('article',null,'project');a.append(node('div',String(i+1).padStart(2,'0'),'project-number'),node('p',x.label,'eyebrow'),node('h3',x.title),node('p',x.description));const tags=node('div',null,'tags');x.tags.forEach(t=>tags.append(node('span',t)));a.append(tags);const details=node('details');details.append(node('summary','Explore technologies'),node('p',x.tags.join(' · ')));a.append(details);if(x.url&&safeLink(x.url))a.append(link('View project ↗',x.url,'text-link'));el('project-grid').append(a);});});
p.publications.forEach((x,i)=>{const row=node('article',null,'publication');row.append(node('span',String(i+1).padStart(2,'0'),'pub-number'));const body=node('div');body.append(node('p',x.venue,'eyebrow'),node('h3',x.title),node('p',x.description));if(x.url&&safeLink(x.url))body.append(link('Read publication ↗',x.url));row.append(body);el('publications').append(row);});
let theme='dark';try{theme=localStorage.getItem('theme-v2')||'dark';}catch{}function setTheme(t){document.documentElement.dataset.theme=t;el('theme').setAttribute('aria-label','Switch to '+(t==='dark'?'light':'dark')+' theme');}setTheme(theme);el('theme').addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';setTheme(theme);try{localStorage.setItem('theme-v2',theme);}catch{}});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');const roles=p.heroRoles||['Machine Learning Engineer','Software Engineer','Multimodal AI Researcher'];let roleIndex=0;el('rotating-role').textContent=roles[0];if(!reduced.matches)setInterval(()=>{roleIndex=(roleIndex+1)%roles.length;el('rotating-role').textContent=roles[roleIndex];},3200);
const sections=[...document.querySelectorAll('main>section[id]')];function move(direction){const current=sections.reduce((best,s,i)=>s.getBoundingClientRect().top<=140?i:best,0);sections[Math.max(0,Math.min(sections.length-1,current+direction))].scrollIntoView({behavior:reduced.matches?'instant':'smooth'});}el('previous-section').addEventListener('click',()=>move(-1));el('next-section').addEventListener('click',()=>move(1));
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('nav a').forEach(a=>{const active=a.getAttribute('href')==='#'+e.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}});},{rootMargin:'-15% 0px -65% 0px',threshold:0});sections.forEach(s=>observer.observe(s));}

// Observe section contents rather than hiding entire long sections.
// Content remains visible if JavaScript or IntersectionObserver is unavailable.
if('IntersectionObserver' in window && !reduced.matches){
 const targets=[...document.querySelectorAll('.section > *, .contact > *')];
 const reveal=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');reveal.unobserve(entry.target);}});},{threshold:0,rootMargin:'0px 0px -35px 0px'});
 targets.forEach((target,i)=>{if(target.getBoundingClientRect().top>innerHeight-35){target.classList.add('scroll-reveal');target.style.setProperty('--reveal-delay',(i%3)*65+'ms');reveal.observe(target);}});
 reduced.addEventListener('change',event=>{if(event.matches){targets.forEach(t=>t.classList.add('is-visible'));reveal.disconnect();}});
}
